package Assignments;

public class Assignment1 {
    // SUPER MARKET BILLING SYSTEM
    // CUSTOMER > 35 YEARS AGE - SILVER
    // CUSTOMER > 45 YEARS - GOLD
    // CUSTOMER > 60 YEARS - PLATINUM
    // CUSTOMER_TYPE = "SILVER" AND BILL_AMOUNT > 5000 - DISCOUNT 5%
    // CUSTOMER_TYPE = "GOLD" AND BILL_AMOUNT > 7000 - DISCOUNT - 8%
    // CUSTOMER_TYPE = "PLATINUM" AND BILL_AMOUNT > 10,000 - DISCOUNT - 10%
}
